### ISSUE TITLE
[feat] Upload Release Java artifacts to GitHub releases

### ISSUE THREAD

**Issue by Lordfirespeed** [aeron-io/aeron#1798]
This would be helpful for e.g. getting the latest version of the Java Media driver for use with the Aeron.NET C# bindings for Aeron.

I am happy to contribute on this.

Usually such an arrangement entails giving Actions access to upload to releases, and then adding the relevant actions step.

## Option 1 for permissions setup - less secure
Give actions 'write' permissions on the repository. 
<img src="https://github.com/user-attachments/assets/10b608c5-80d0-4873-87aa-b37cffb4f92b" alt="Image" width="500">

## Option 2 for permissions setup - more secure
A user with write access to the repository creates a 'fine-grained' Personal Access Token [here](https://github.com/settings/personal-access-tokens/new):
- Resource owner -> `aeron-io`
- Expiration -> custom -> 1 year
- Repository access -> selected repositories -> this repository
- Repository permissions -> 'Contents' -> 'Read and Write'
<img src="https://github.com/user-attachments/assets/b2c43581-135d-413d-8395-326d72160ee2" alt="Image" width="500">

The generated PAT is added as a new 'repository secret' [here](https://github.com/aeron-io/aeron/settings/secrets/actions)
<img src="https://github.com/user-attachments/assets/4bef63df-d3b9-4481-9a12-e114d46e5674" alt="Image" width="500">

## Add step to Release workflow

```yml
- name: Upload artifacts to Release
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # if permissions option 1
    GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}  # if permissions option 2
  run: gh release upload ${{ TAG NAME EXPRESSION }} [file paths...]
```

`TAG NAME EXPRESSION`
- For workflow runs triggered by `release` event, `github.event.release.tag_name` will expand to the tag name
- For workflow runs triggered by `push` event with `tags` filter, `github.ref_name` *should* expand to the tag name ( I am not certain, but relatively confident )
